### ISSUE TITLE
Uploading files with long filename impossible

### ISSUE THREAD

**Issue by tedstriker** [jonaswinkler/paperless-ng#109]
While testing paperless ng I found an error preventing uploads of files with (really) long file names.
As a consequence the file is not added to paperless and not removed from the consume directory.
`2/8/20, 7:17 PM ERROR The following error occured while consuming Das virtualisierte MacOS installieren - Catalina und Big Sur_ MacOS als virtuelle Maschine unter Linux - Golem.de.pdf: value too long for type character varying(50)`
The same happens if you try to upload the file by file upload in the browser and no error is shown.

My expectation was: If no automated processing based on the filename is possible, the file should still be added to the inbox.

**Comment by jonaswinkler** [comment]
I assume you are using PostgreSQL?

**Comment by tedstriker** [comment]
Sorry for the lack of technical details. You are correct. I spun up the docker compose stack with PostgreSQL in the backend.

**Comment by jonaswinkler** [comment]
No worries, I know exactly what's going on. This is correlated with #83. It's not the actual filename that's causing the issue, rather the information paperless tried to extract from the filename. Paperless has this weird mechanic where it slices filenames up according to some predefined patterns and assumes that these slices represent correspondent / title / tags and so on. In this case, it tried to make a correspondent from "Catalina und Big Sur_ MacOS als virtuelle Maschine unter Linux", which is longer than 50 characters.

First of all, that limit is rather low.

Second: I don't see that this feature is particularly useful (at least no one has reported successful usage yet), and I'm considering to remove that entirely. This is also why this problem might take a bit longer to get resolved.

In order to work around this for now, remove the dashes from the filename.
