### ISSUE TITLE
Feature Request: Tag Browsing

### ISSUE THREAD

**Issue by shamoon** [jonaswinkler/paperless-ng#110]
First of all bravo on this project, I had been unhappy with all of the DMS options out there and paperless-ng is really starting to look like the right horse to hitch my wagon to. Appreciate all your hard work and the fever-pace of work! I hope it gets merged into the main project. I dont have time to work on a PR for this right now but hope to contribute at some point.

I was looking for an easier way to browse tags, almost like a folder tree. Even adding a simple section TAGS above MANAGE (and perhaps these sections need to become collapsible) would work. Just a listing of all tags for now, once nested tags are implemented might be more complicated. Obviously there are other ways to get to the tags currently but I think a lot of people use them like this. Similarly implemented in [Teedy](https://github.com/sismics/docs) and [docspell](https://github.com/eikek/docspell)

Thanks again for everything!

**Comment by jonaswinkler** [comment]
Just out of interest. What exactly made you unhappy with the existing solutions?

Regarding this: putting this off until nested tags. The left sidebar isn't really the correct place for this, since this provides top-level navigation. We could put the tags in there, but these links would do something different (i.e., not switch to a different view, but rather modify the current one). They would also not highlight when clicked and the menu is already kinda packed with a couple saved views and opened documents.

We'd need to put that somewhere else so that the UI remains intuitive. I agree that having quick access to tags would be nice. Clicking visible tags for filtering is nice, as long as the one you're looking for is in view.

Perhaps: Work on the filter, reduce the amount of clicks needed. Maybe separate the available filters so that some of them (tags, correspondents, types come to mind) are immediately accessible, without selecting them from a drop down, clicking add, selecting the tag in question, and then pressing apply. Need a modified UI for that.

**Comment by jonaswinkler** [comment]
Just out of interest. What exactly made you unhappy with the existing solutions?

Regarding this: putting this off until nested tags. The left sidebar isn't really the correct place for this, since this provides top-level navigation. We could put the tags in there, but these links would do something different (i.e., not switch to a different view, but rather modify the current one). They would also not highlight when clicked and the menu is already kinda packed with a couple saved views and opened documents.

We'd need to put that somewhere else so that the UI remains intuitive. I agree that having quick access to tags would be nice. Clicking visible tags for filtering is nice, as long as the one you're looking for is in view.

Perhaps: Work on the filter, reduce the amount of clicks needed. Maybe separate the available filters so that some of them (tags, correspondents, types come to mind) are immediately accessible, without selecting them from a drop down, clicking add, selecting the tag in question, and then pressing apply. Need a modified UI for that.

**Comment by jonaswinkler** [comment]
What also comes to mind: some people have lots of tags. or correspondents. I found the sidebar filters in django quite annoying to scroll through.

Therefore: maybe allow "pinning" of tags, which would simply create a saved view, which filters by that tag and is named just like the tag.

**Comment by jonaswinkler** [comment]
And yet another idea that I had a couple days ago regarding this:

On the management pages, provide a button "View" next to the edit / delete buttons that would instantly bring up the document list filtered by that tag / type / correspondent.

**Comment by shamoon** [comment]
These are all fantastic ideas. Its not so much that current solutions make me "unhappy" 😀 just that I find myself wishing they were easier to get to. I realize things like server-side saved views (#101) and search improvements (#74 #79) will improve things a lot anyway. I think the current tools are a little more geared towards "power users" like ourselves whereas something like a visual filter UI is more geared towards less tech-savvy users (in my case, other members of my family).

- Agree surfacing tags in the filtering UI would go a long way, perhaps just including something at the top of the Documents view would be enough. Nested tags will likely complicate this UI-wise.
- Pinning would be a great way to reduce clutter if it ends up in sidebar but then there really isnt much difference between a 'pinned tag' and 'saved view'.
- View button on management pages is definitely a good idea just as a sort of extra way to get there.

**Comment by shamoon** [comment]
Ps. Another idea for filter UI, perhaps we can take some ideas from Github UI (see attached screenshot). Add buttons / dropdowns for "tags" "correspondents" that reveal scrollable and / or filterable list of items. Kinda fancy but works nice and keeps things un-cluttered.
<img width="1276" alt="Screen Shot 2020-12-08 at 2 50 20 PM" src="https://user-images.githubusercontent.com/4887959/101550858-e49ded00-3964-11eb-9ef2-940712887eb4.png">

**Comment by jonaswinkler** [comment]
Well yeah, that's the way to go. When I look at these kind of views, it's so obvious that I'm not a UX guy :-)

The first draft of the UI for paperless actually had tags and correspondents in the side bar and I did not like it at all.

> * Pinning would be a great way to reduce clutter if it ends up in sidebar but then there really isnt much difference between a 'pinned tag' and 'saved view'.

Yes. It would be a shortcut for something that's already possible.
