### ISSUE TITLE
{created_day} & {created_day} Filename with 01 instead of 1 (DD instead of D and MM instead of M)

### ISSUE THREAD

**Issue by ministryofsillywalks** [jonaswinkler/paperless-ng#117]
I like having my files in a human readable fashion, that's why I have paperless naming my files:
`{created_year}{created_month}{created_day}-{correspondent}-{document_type}-{title}`
My expectation would be that 01 Dec 2020 would  by 20201201 YYYYMMDD and not 2020121 YYYYMMD as this messes sorting in the explorer. Or in worst case 01. Jan. 2020 being 202011 YYYYMD
![image](https://user-images.githubusercontent.com/10544895/101763978-cc9ea880-3adf-11eb-85bb-2ed98f775752.png)
As you can see here a document from 2018 sorts higher than one from 2020.

**Comment by jonaswinkler** [comment]
I see.

There's also `{created}` which uses the ISO format (YYYY-MM-DD).

For the time being, you can also do this:

`{created_year}{created_month:02}{created_day:02} {title}`

The `:02` part tells paperless to use leading zeros and use at least two digits. However, I might change that so that paperless always adds leading zeros, which will render this format invalid, so keep an eye out on change logs.

**Comment by jonaswinkler** [comment]
Will be fixed in the next release. Please don't use the above mentioned workaround anymore.

**Comment by ministryofsillywalks** [comment]
Using {created} at the moment.
That's still going to be supported?

**Comment by jonaswinkler** [comment]
Yes, always.
