### ISSUE TITLE
Auto Increment Archive Serial Number?

### ISSUE THREAD

**Issue by aboutte** [jonaswinkler/paperless-ng#121]
First, thank you very much for the work you are putting in here!  I am finally getting to scratch a decade long itch!

I have paperless up and running, I got my scanner today, and I am working through establishing my workflow.  Correspondence, tags, and document types are all making sense and I have a system I like.  Going through your documentation I really like the idea of keeping hard copies of some docs and having an identifier to tie the digital and physical docs together.  

What I can't understand is why I have to set the ASN.  It seems like the workflow would have to include a step to either go to the physical filing cabinet and browse through paperless each time to figure out the next ASN.  

What am I missing here?  From my limited use I don't see a use case where I want to manually be able to set the ASN.  I would prefer to:

- scan a pile of docs
- decide which I need to physical keep
- get the auto assigned ASN from paperless
- write the ASN on doc
- file the doc away

I would appreciate any context I may be missing.

**Comment by jonaswinkler** [comment]
I... think you assume that this ASN should get assigned to every document? That's possible, but not exactly how I imaged it would be used. The presence of that number tells you that a) the physical version of this document still exists and b) where it is.

I write the identifier on the documents before scanning them. Look up the last one, since I already have the physical binder ready for archiving anyway, and do +1. That way, both the digital and physical versions are permanently tied together. The ability to enter that number in paperless is for better visibility in lists. This way, the numbering within the physical binder has no gaps as well.

Assigning that number automatically is somewhat difficult, since paperless does not know when you keep a document and when you throw it away.

That's how I've been doing it and it's working out for me, however, your approach sounds valid as well and I'd consider adding an option to auto-assign and increment that number.

**Comment by aboutte** [comment]
Yes in my mind I was thinking the ASN would get auto assigned to every document.  I understand why it works this way now that I better understand your workflow.  You sound much more organized than myself having the physical binder ready :) 

I will continue to play around with my workflow to see if it would be easier to have it auto assigned or not.  

I guess worse case I could grab the paperless document ID from the URL and manually assign it to the ASN.

**Comment by jonaswinkler** [comment]
Simplest solution and dead-easy to implement would be to just set ASN = ID on document creation, configurable with a switch. I just don't exactly know if that's really required.

**Comment by aboutte** [comment]
Thinking through it more I agree that it does not make sense to assign an ASN to every document.  What about changing the ASN text field to an "Assign ASN" button and paperless increments the ASN for us?

**Comment by jonaswinkler** [comment]
We could have that button in addition to the text field. Look up the highest used number, do +1, assign. Although, this would require you to process your inbox in the order of scanning.

**Comment by ghaberek** [comment]
I don't really plan to make use of the ASN field, so it would be nice to be able to turn off the "ASN" column from the list view.

**Comment by jonaswinkler** [comment]
Let's take that one step further and allow users to customize all columns in the list view.

**Comment by kaiserbene** [comment]
> 
> 
> We could have that button in addition to the text field. Look up the highest used number, do +1, assign. Although, this would require you to process your inbox in the order of scanning.

that would be very helpfull - i scanned bunch of docs, sorted the ones i want to keep. Now i have to check manually for the latest ASN - a "+1" button would make life easier.

**Comment by jonaswinkler** [comment]
![image](https://user-images.githubusercontent.com/17569239/103491575-47c85580-4e25-11eb-8284-27a69f3c4596.png)

looks up highest ASN, does +1 and sets the field.

**Comment by aboutte** [comment]
This looks great!
