### ISSUE TITLE
[BUG] Fresh Installation AT Raspi throws Password mismatch error

### ISSUE THREAD

**Issue by Dark-Gizmoa** [jonaswinkler/paperless-ng#1220]
**Describe the bug**
Fresh Installation of Paperless-ng by "Easy Install Docker Script"; Error: Password did Not match

**Expected behavior**
Starting of Installation Wizard

**Relevant information**
 - Host OS of the machine running paperless: [Raspberry OS, latest] 
 - Installation method: [easy install docker script]

**Comment by IxFail** [comment]
Had the same problem with my Ubuntu machine, instead of using the following command `curl -L https://raw.githubusercontent.com/jonaswinkler/paperless-ng/master/install-paperless-ng.sh | bash`
Use the following:
`wget https://raw.githubusercontent.com/jonaswinkler/paperless-ng/master/install-paperless-ng.sh`
Then grant exection rights to the file: `sudo chmod +x install-paperless-ng.sh`
Then execute the shell file: `./install-paperless-ng.sh`

**Comment by Dark-Gizmoa** [comment]
@IxFail
Thanks.
With your tip it is running perfectly.

Greetings
