### ISSUE TITLE
Generate TOC for binder from ASN?

### ISSUE THREAD

**Issue by vestingz** [jonaswinkler/paperless-ng#126]
Hi,
thank you for this nice project! :)

My question is rather workflow related: is it possible to generate some sort of table of contents from ASN e.g. 1 - 343 to have some sort of backup index in case paperless goes down? I'd like to print this TOC and put it together with all the documents in the binder then.

Thank you again!

**Comment by jonaswinkler** [comment]
Very good idea!

I'd have to look into how to actually create PDF documents from raw text / formatted text. I'd also have to consider where to put that in the UI so that it does not get in the way.

However, since this project is apparently picking up some momentum, I'd like to address more pressing issues first.
