### ISSUE TITLE
Feature Request: 2 factor authentication

### ISSUE THREAD

**Issue by zjean** [jonaswinkler/paperless-ng#142]
Hi,
First of all, thank you very much for this awesome project. Sometime ago I decided to not use paperless, but now I see paperless-ng, with its really nice and fast UI, I am glad I found it.

I would very much like a two factor authentication feature to increase security of the system. I am used to TOTP, but any other implementation might work as well.
What do you think?

PS It would be useful for me to see the name (or avatar) of the current user somewhere in the UI. Maybe in the top right corner (like github).

**Comment by Tooa** [comment]
Do you want 2FA, because you plan to expose the WebUI to the Internet? If so I'm not sure whether this is a good idea from a security perspective. Instead, I would hardly recommend a VPN connection instead.

**Comment by jonaswinkler** [comment]
I think the user interface of old paperless turned a lot of people away. Glad you like it.

I'm no expert on security, and can only warrant security as far as the default authentication mechanisms of the used framework (which is named `Django` and is fairly big) go. These are used to guard paperless, and I did nothing fancy in that regard. Actually, with regards to the license, I don't warrant anything, so use at your own risk.

Regarding two factor authentication:

* I agree that this is a good thing to have.
* I've looked into how to get that into paperless. There's a package that already has all this functionality (it even has some option to use SMS or voice call authentication, not sure how that works) and is well maintained. Integration with paperless seems fairly simple. This is a good thing.
* However, we also have some mobile Apps out there. These use a different interface to paperless for authentication, and I need to look into how to provide two factor authentication at these interfaces as well, otherwise it would not make much sense.

**Comment by shamoon** [comment]
FWIW you can put paperless-ng (or anything) behind something like [Authelia](https://www.authelia.com/) and get 2FA and SSO. Makes it less important to me that each app have its own. (And once I do it myself for paperless-no I will make sure they integrate properly.)

**Comment by jonaswinkler** [comment]
Closing this as out of scope, since there are other applications that are able to handle this for paperless.

**Comment by hammermannman** [comment]
> Closing this as out of scope, since there are other applications that are able to handle this for paperless.

Hey
I am not an expert and it is quite difficult to setup something like authelia..
Is there in the meantime something new about 2FA for Paperless?
