### ISSUE TITLE
FR: Searchable dropdowns

### ISSUE THREAD

**Issue by zjean** [jonaswinkler/paperless-ng#152]
As the list of correspondents might grow, it would be nice to be able to search in the correspondents dropdown.
For example by using [Select2](www.select2.org) or something else.

**Comment by shamoon** [comment]
this is already done in #111 =)

**Comment by jonaswinkler** [comment]
No. Searchable drop downs when editing documents.

**Comment by shamoon** [comment]
Ahh, this is probably a good idea for all of those dropdowns.

**Comment by jonaswinkler** [comment]
I'd like to use [ng-select](https://www.npmjs.com/package/@ng-select/ng-select) for this, since this

- is reasonably popular, and sees regular updates
- has filtering
- has better tag editing than what we have right now
- apparently supports some form of nested selections, which might be useful later.

**Comment by shamoon** [comment]
I can take a look at this if you've got other stuff

**Comment by shamoon** [comment]
Cool, check out PR #154 , I think it worked out well
