### ISSUE TITLE
[BUG] Tika container cannot start on Raspberry Pi4

### ISSUE THREAD

**Issue by FredNov** [jonaswinkler/paperless-ng#1528]
**Describe the bug**
Tika container constantly restarting.

**To Reproduce**
1. Download docker-compose.postgres-tika.yml
2. docker-compose up 
3. Container starts and then immediately exits with the following error

command `docker logs -f paperless-tika-1` shows

standard_init_linux.go:228: exec user process caused: exec format error
standard_init_linux.go:228: exec user process caused: exec format error
standard_init_linux.go:228: exec user process caused: exec format error
standard_init_linux.go:228: exec user process caused: exec format error
standard_init_linux.go:228: exec user process caused: exec format error

**Expected behavior**
The container should be up and running

**Relevant information**
 - I'm using Raspberry PI 4
 - Linux magicmirror 5.10.63-v8+ #1496 SMP PREEMPT Wed Dec 1 15:59:46 GMT 2021 aarch64 GNU/Linux
 - Installation method: docker

**Comment by nbently** [comment]
This is probably because the tika images aren't built for arm (RPi architecture). Check out https://github.com/abhilesh/apache-tika-arm. It looks like they created these tika images specifically so tika would work with paperless-ng on an RPi. Looks like they also made available some template files for running paperless on an RPi: https://github.com/abhilesh/self-hosted_docker_setups/tree/main/paperless-ng.
