### ISSUE TITLE
Show in the logs what matched for tag/doc type/correspondent

### ISSUE THREAD

**Issue by Sup3rlativ3** [jonaswinkler/paperless-ng#161]
**What:** Add a section in the logs menu (or possibly in the document details section) that shows what in the particular document triggered the assignment of the tag/doc type/correspondent.

**Why:** There have been occasions, even in my very short usage, where a tag was assigned but I couldn't find any of the match criteria in the document. It would be useful to know why certain things matched so that you could tweak your match statements. I'm sure that those of us that use regex would certainly appreciate it.

I've had a look at the logs in the interface as well as the docker logs but I don't see anything there that provides any information about what string was matched for the assignment.

**Comment by jonaswinkler** [comment]
That's part of the reason I put in automatic matching. It's very difficult to get these matching rules right.

I can't realistically put that into the document detail page, since: rules, as well as the content of the documents might change and I'd therefore need to store content, rules and their matches at the time the document was consumed, and I don't exactly want to add database fields for that.

However, I can add some more log messages for when and why certain tags/correspondents and types were assigned. Possibly a link to the logs relevant to a particular document on the document detail page as well.

**Comment by Sup3rlativ3** [comment]
I can understand the automatic matching being added but sometimes it just doesn't suit.

It would be great to have a simple log message like:
```
[2020-12-20 00:00:00 +10:00] Tag {MyTagname} matched to string "Here is my string that triggered the rule"
```

If you had the ability (I'm not sure it's easily possible), it would be awesome to also have the part of the pattern that matched e.g.

```
Name: MyTagName
Match: "abc" "\d{4}.\w{3}"

[2020-12-20 00:00:00 +10:00] Tag {MyTagname} matched <\d{4}\w{3}> to string "1234abc"
```

**Comment by jonaswinkler** [comment]
I'll look into it, that's not all that difficult.
