### ISSUE TITLE
Donation link

### ISSUE THREAD

**Issue by Sup3rlativ3** [jonaswinkler/paperless-ng#167]
I think it would be nice if you had a way for people to donate for the work you've done. Something like bitcoin/librapay.

I understand some people don't like to accept donations as they feel obliged to do things if there is money involved. If that's the case, a simple disclaimer at the bottom of the README would suffice or perhaps there's a charity you could direct people to?

**Comment by jonaswinkler** [comment]
I could setup a GitHub Sponsor account and put that on the site no problem. I'd put a disclaimer somewhere that even with that, there's no warranty on the project whatsoever, regarding data safety, and being active in a couple years. That said, *I do care* for the project, since I use that myself and won't switch anytime soon.

I'm not sure yet how I feel about that. Since this is a follow-up project to [paperless](https://github.com/the-paperless-project/paperless), I'd like to continue working on that in the spirit of the original project, and @danielquinn has redirected all donation requests to a charity mentioned in the project readme, so I think I'll do that as well.

**Comment by danielquinn** [comment]
For what it's worth, I think it's a good policy for collaborative projects to allow/encourage the funding of individual developers through something like [BountySource](https://www.bountysource.com/): the person who does the job gets the bounty.  Having a project centrally collect funds though means that it has to distribute them to the team and determining who-gets-what share is a toxic nightmare.

That's why I opted for the charitable donation option and added the `THANKS.md` file if anyone felt like saying thank you (though it was never used 😢)  As paperless-ng is still largely your baby (your contributions are clearly a significant addition to the original project) you could make a case to have people donate directly to you to continue development, but you run the risk that you might alienate other would-be contributors while you argue over why some contributions get money and some don't.

At the end of the day, I wrote Paperless 'cause I had a need for it and because it was fun.  There was never going to be a case where I would get paid enough to live off of the donations, so I figured that the charitable option was the best choice.

**Comment by jonaswinkler** [comment]
Good advice. I'll dodge that entire problem then by simply not accepting any money whatsoever. Without looking too much into it, BountySource also comes with issues. If someone posts a really huge bounty on a feature that I don't really see being a part of the project, and someone implements it, then who am I to say they don't get the bounty by not merging that feature.

**Comment by danielquinn** [comment]
Yeah that's a sticky one too.  Maybe you could go the route of tagging issues as "bountyable" or something?  I don't know.  Hell, if I'd solved this problem, I might still be actively working on Paperless ;-)  I'm going to keep an eye on -ng though 'cause it's exciting to see where things are going.

**Comment by mtlynch** [comment]
Just want to add that if you set up a Patreon or some sort of recurring subscription, I'd contribute $10/month because I want to fund this project and pay you for your time maintaining it. I don't need any special privileges or features in exchange. I suspect others are in the same boat.
