### ISSUE TITLE
Filters for "None" document type and correspondent

### ISSUE THREAD

**Issue by agrider** [jonaswinkler/paperless-ng#186]
Can we add a toggle to the main Documents filter bar to filter by documents with no correspondent or no document type? I'd like to create a view for documents with no Document Type and/or no Correspondent, but the only options in the Document Type and Correspondent dropdowns currently are for the options you add, there is no None option in either dropdown, preventing creation of views for this purpose.

**Comment by shamoon** [comment]
Ah interesting. @jonaswinkler I think this would need an API update, yea? I think there's currently no way to explicitly search for "Correspondent = nothing". If you'd like I can do the front-end stuff once you have the back-end sorted (assuming you want to implement this), lemme know.

**Comment by jonaswinkler** [comment]
Not sure, have to check.

**Comment by jonaswinkler** [comment]
there's now query args "correspondent__isnull" and "document_type__isnull" for that. In the ui, simply set the correspondent / document type of the corresponding filter rule to `null`. Might as well do this for tags, however, we'd have to explicitly use "is_tagged=false" rule instead of "has_tag" rules.

**Comment by shamoon** [comment]
Cool, I'll take care of it. @jonaswinkler one thing is that because `feature-bulk-edit` contains significant refactoring of some of the components the `FilterEditor` uses do you think we can merge `feature-bulk-edit` into `dev` or not yet? That would just make it easier to make these changes and not have a more complicated merge later.

**Comment by jonaswinkler** [comment]
I'll get that bulk editor sorted first.

**Comment by jonaswinkler** [comment]
done! :)

**Comment by shamoon** [comment]
Oh I already had this ready to go, didn't realize you took care of it =/
Oh well.

**Comment by jonaswinkler** [comment]
Much of the logic changed, so unless you did this on the `dev` branch after my rework of the filter drop downs, I don't know how much could have been reused anyway.

**Comment by agrider** [comment]
You guys are awesome, thanks!
