### ISSUE TITLE
Download all selected documents as compressed archive

### ISSUE THREAD

**Issue by Exordian** [jonaswinkler/paperless-ng#211]
Occasionally I need to export a bunch of documents for offline usage (e.g. a bunch of travel documents, some clinical reports, ...).

A feature which downloads mulitple selected documents (part of the bulk edit function?) would be nice.

**Comment by jonaswinkler** [comment]
Agreed, this seems useful.

Should they be downloaded as a single zip-compressed file?

**Comment by shamoon** [comment]
Yea agreed. Zip makes sense to me as it could potentially be many items. Let me know if you’d like any assistance with this one JW

**Comment by jonaswinkler** [comment]
Hm. I just wondered how we should handle cases when a user decides to press download while having 1000+ files selected. That's going to take a while.

**Comment by shamoon** [comment]
Yea good question. Im a believer that you can only protect users so much from making poor choices =) I suppose the complicated route would be to setup an export queuing system but that just seems way overkill. 

Correct me if Im wrong but I'd guess the time to generate a zip will increase linearly with file size (rather than N files) and will probably vary significantly depending on the host machine (i.e. no real way to know how long it will take for a particular install)?

So maybe we find some reasonable threshold (100mb, 500mb? No idea really. Or maybe its a setting?) and when the user initiates an export larger than that we throw up a modal warning, something like "this could take a long time or even fail with such a large export, are you sure?". We could see how well that serves people (again who knows how much people are going to use this feature in general) and always readdress later if everyone thinks it needs to change.

Just a thought?

**Comment by jonaswinkler** [comment]
I went the easy route and just zip up the selected documents without compression. That's fast, and in *most* cases the files stored in paperless will already be compressed anyway (PDFs produced by OCRmyPDF are, JPGs are, PNGs are, not sure about TIFF). No progress bar or so for now, since that's difficult :)
