### ISSUE TITLE
Error when importing pdf

### ISSUE THREAD

**Issue by zjean** [jonaswinkler/paperless-ng#213]
Hi,
I added a pdf (via the file upload in the web interface) and got this error in the logs:
12/29/20, 10:10 PM ERROR The following error occured while consuming [redacted].pdf: UNIQUE constraint failed: documents_document.checksum

How is this checksum calculated?
I have imported the same document before, but that failed with this error:
12/16/20, 8:32 PM ERROR The following error occured while consuming [redacted]pdf: database is locked

I am using sqlite.
It looks like the database got currupted.

**Comment by jonaswinkler** [comment]
This happens if paperless starts consuming the same document twice. Example: file.pdf gets uploaded, paperless starts OCR. file.pdf gets uploaded again or is put into the consumption directory: paperless processes that file as well, and starts OCR. OCR on the first document finishes, the document is saved. OCR on the second document finishes, but paperless finds that this document already exists, yields an error, and throws away all intermediate results.

If you think that this does not apply to you, then this is an error and I need to investigate. However: Whenever the consumer encounters database errors, it will roll back all changes and not leave the database in an intermediate state.

Checksum is an MD5 checksum on the original file.

These errors don't indicate a corrupt database.

If you want to check your document collection, you could manually invoke the sanity checker (which checks existence of all documents, thumbnails, their checksums, etc) by going to Admin, then Scheduled tasks, then Perform sanity check, and at "Next run" click on Today and Now, then Save. This will tell paperless to run the sanity checker within the next minute. The result will be available either on "Successful tasks" or "Failed tasks", depending on the outcome.

This will eventually be more accessible.

**Comment by zjean** [comment]
Thanks!
The first import was more than a week ago, so the imports didn't run at the same time.
 I ran the sanity checker, that didn't report any errors.
I will check if I can re-upload the file tomorrow.

**Comment by zjean** [comment]
This was my mistake. The document did already exist in paperless.

**Comment by jonaswinkler** [comment]
I'll look into making the error messages more clear about what's happened.
