### ISSUE TITLE
Search bar styling

### ISSUE THREAD

**Issue by jonashaag** [jonaswinkler/paperless-ng#217]
Just installed paperless-ng using the Docker method. It works fine, however, search seems to only apply to the document title? If I type something into the "Filter by" search bar it finds 0 results even though the word I've typed in is one of the documents' "Content" tab.

**Comment by jonashaag** [comment]
<img width="232" alt="Screenshot 2020-12-30 at 14 05 51" src="https://user-images.githubusercontent.com/175722/103353076-27586e00-4aa8-11eb-9206-a4cff896d3f3.png">

**Comment by wikitaube** [comment]
Hi jonashaag, 
the Full-Text-Search is a bit hidden.
There is a Full-Text-Search on the top of the page .
![full-search](https://user-images.githubusercontent.com/41522834/103353411-1b20e080-4aa9-11eb-9039-90c26b142949.png)

In my example i searched for electronics.

**Comment by jonashaag** [comment]
Oh... didn't see that at all. Ignored it because it looked like it's part of the page header.

Maybe a simple color change can make it more visible.

**Comment by jonaswinkler** [comment]
hm, it even says "Search for documents" when nothing is typed in there.

**Comment by jonashaag** [comment]
<img width="1449" alt="Screenshot 2020-12-30 at 14 46 15" src="https://user-images.githubusercontent.com/175722/103355201-faa75500-4aad-11eb-9442-274b118709ab.png">

That's how it shows for me. Must be the most subtle search bar I've ever seen, for a tool that's supposed to be search centered.

**Comment by jonaswinkler** [comment]
Do you have any advice on how to make it more visible?

**Comment by jonashaag** [comment]
I'm a terrible designer. How about something like that?

<img width="626" alt="Screenshot 2020-12-30 at 15 06 38" src="https://user-images.githubusercontent.com/175722/103356221-a81b6800-4ab0-11eb-91b9-62e3b021b9ca.png">

- Search icon (used tag icon for this example)
- Grayish border
- Lighter background (`0.1` -> `0.2`)

**Comment by jonaswinkler** [comment]
@shamoon, whats your take on this?

**Comment by jonashaag** [comment]
I think the main reason I didn't find the search bar is because it's a very unusual position: sort-of left aligned and covering almost the entire width of screen. Usually search bars are right-aligned, much smaller, and have different color than the header

**Comment by ghaberek** [comment]
> I'm a terrible designer. How about something like that?
> 
>     * Search icon (used tag icon for this example)
>     * Grayish border
>     * Lighter background (`0.1` -> `0.2`)
>     * More text

I think this is good, and I'd also recommend:

- Add rounded corners so it looks the same as other fields and buttons.
- Update the icon to be a magnifying glass (the de facto "search" icon).
- Update the placeholder text to say _Search for documents_ instead of just _Search_.
- Reduce the margins in a bit more to make a better distinction between the field background and the header background.
- Make it the same height as the **Filter by** field as well? On my screen this is 38px for **Search** and 31px for **Filter by**.
- Show the current user on the right of the header to bring in the right margin of **Search** field from the edge of the page.
- Make the current user display a menu and move _Admin_ and _Logout_ links here.

**Comment by shamoon** [comment]
I suppose I didn’t have as much trouble as others but I agree it’s subtle. I think there are actually two issues here:

- Current search bar design is subtle
- The other thing is that because the 'filter bar' doesnt include searching text it might throw people off, I think that's what happened to OP.

The first one is straightforward, I ageee with much of the suggestions here, I think there are many ways to improve this. The second one is a bit more of a discussion and would also require reworking some of the app. I think it would be reasonable to just tackle the first for now, though it probably would be useful to be able to filter search results (and vice versa so presumably unify them).

As you know by now @jonaswinkler I'd enjoy working on any / all of this once we're decided.

**Comment by jonaswinkler** [comment]
> though it probably would be useful to be able to filter search results (and vice versa so presumably unify them).

Not going to happen anytime soon. When I added the full text search a couple months ago I actually tried this and came to the following conclusions.

- Both systems use a completely different approach internally to retrieve documents.
- Search results are always sorted by score, so the other sorting options won't have any effect here.
- Filtering works differently.
- Search results provide different data that's not available when querying the database.
- Pagination works differently.

This would be a huge undertaking, since all this implies that we can't really use all the handy tools that `django rest framework` is offering.

> As you know by now @jonaswinkler I'd enjoy working on any / all of this once we're decided.

Go ahead, make it beautiful. I'm glad you're around to fix up my messy css stuff.

**Comment by shamoon** [comment]
I figured merging them was much bigger than it might seem. Great, will work on the search bar and get back to the group.

**Comment by shamoon** [comment]
One question I wanted to ask the group about. The size of the search will definitely shrink in width to make it more visible, which potentially makes the entire top bar much less useful. Distilling other suggestions / logical choices:

1. We can just drop the right half of the top navbar completely and move the main document area up by those ~50px. This would mean moving the search perhaps to the sidebar.
2. We can add other stuff to the navbar to keep it useful. The most obvious stuff to go here, as someone suggested, is a user menu under which we can put "Logout" and / or Settings and / or Admin.

There are pros / cons to either but I think the second option makes the most sense, in particular I think the paradigm of "user dropdown in the top right corner" is so well-known to people it will feel familiar. You good with that @jonaswinkler ?

**Comment by jonaswinkler** [comment]
Sure!

**Comment by shamoon** [comment]
This is where Im at currently, #.2 from above seems to work best, otherwise sidebar gets cramped. 

Nothing crazy here, I think its just about simplifying some visual elements e.g. dark background on brand, adding some more space, differentiating the search. Mobile works great, I debated hiding search under the dropdown but left it like this because I think its actually the easiest way to get to docs on a mobile device.

Welcome any / all feedback, of course

<img width="1093" alt="Screen Shot 2020-12-31 at 12 00 39 AM" src="https://user-images.githubusercontent.com/4887959/103401184-c444f680-4afc-11eb-82f3-891f049647a6.png">
<img width="483" alt="Screen Shot 2020-12-31 at 12 00 12 AM" src="https://user-images.githubusercontent.com/4887959/103401180-c3ac6000-4afc-11eb-9762-c8148c9fec98.png">
![searchanim](https://user-images.githubusercontent.com/4887959/103401186-c4dd8d00-4afc-11eb-8c35-b83465a21d2e.gif)
.

**Comment by jonashaag** [comment]
That's SO MUCH better, thanks! <3

The only criticism I have is that on Desktop the left-hand border of the search bar is not aligned with any of the other visual lines (eg. the sidebar right-hand border or the Dashboard "D")

**Comment by shamoon** [comment]
Heh I noticed that too and fixed but was too lazy to take new screenshots. Sharp eyes! 👀

**Comment by ghaberek** [comment]
> Welcome any / all feedback, of course
> 
> <img alt="Screen Shot 2020-12-31 at 12 00 39 AM" width="1093" src="https://user-images.githubusercontent.com/4887959/103401184-c444f680-4afc-11eb-82f3-891f049647a6.png">

That looks fantastic! Only thing I would add maybe is the user name next to the icon for the menu.

**Comment by shamoon** [comment]
Thanks! 

Yea I debated that but in the end felt it was clutter and putting it inside the actual dropdown. There is room to show it on desktop (and hide on mobile) but I couldn’t really justify why it would actually be important to see at the top level... Unless people feel strongly?

**Comment by ghaberek** [comment]
> There is room to show it on desktop (and hide on mobile) but I couldn’t really justify why it would actually be important to see at the top level... Unless people feel strongly?

Personally when designing user interfaces I try to use labels as often as possible to avoid confusion and ambiguity.

https://uxdesign.cc/when-should-i-be-using-icons-63e7448202c4

> 6. "When in doubt, always remember this: [the best icon is a text label](https://thomasbyttebier.be/blog/the-best-icon-is-a-text-label)."

**Comment by shamoon** [comment]
Certainly true but this is _such a convention_ that I wasnt sure its necessary. I certainly dont feel strongly about it so Im happy to change, but ya know:

Github:
<img width="236" alt="Screen Shot 2020-12-31 at 3 46 37 PM" src="https://user-images.githubusercontent.com/4887959/103431075-8341f600-4b7f-11eb-97c6-022e35d27b02.png">

Gmail:
<img width="224" alt="Screen Shot 2020-12-31 at 3 47 13 PM" src="https://user-images.githubusercontent.com/4887959/103431077-86d57d00-4b7f-11eb-883f-44cfa1ed078f.png">

Yelp:
<img width="244" alt="Screen Shot 2020-12-31 at 3 49 26 PM" src="https://user-images.githubusercontent.com/4887959/103431109-ecc20480-4b7f-11eb-92a0-8cef00715d52.png">

Etsy:
<img width="316" alt="Screen Shot 2020-12-31 at 3 50 52 PM" src="https://user-images.githubusercontent.com/4887959/103431117-f8adc680-4b7f-11eb-8a75-34b9f4a39ef4.png">


I realize there are many sites that do, seems like a toss-up!

**Comment by shamoon** [comment]
So:

<img width="1073" alt="Screen Shot 2020-12-31 at 4 07 25 PM" src="https://user-images.githubusercontent.com/4887959/103431265-5cd18a00-4b82-11eb-9322-857500fa2540.png">
<img width="440" alt="Screen Shot 2020-12-31 at 4 15 07 PM" src="https://user-images.githubusercontent.com/4887959/103431356-5ee81880-4b83-11eb-898c-0e14241a608e.png">

**Comment by jonashaag** [comment]
Thanks everyone ❤️
