### ISSUE TITLE
Feature Request: Rotation in App

### ISSUE THREAD

**Issue by isentropik** [jonaswinkler/paperless-ng#228]
Hey! I have a few images that I missed rotating while saving. Would it be possible to add a rotate feature so that the OCR doesn't spit out a garbled mess?

**Comment by jonaswinkler** [comment]
This would involve recreating the documents in paperless from scratch. With the way paperless is implemented right now, I'd essentially have to delete the document, and go through the consumption process again, since this affects everything about the document (original file changed, checksum changed, content changed, thumbnail changed, converted PDF changed, matched metadata changed due to changed content, search index changed, ...)

How many images are we talking about? You can always download the original image and correctly rotate it yourself.

**Comment by isentropik** [comment]
All excellent points. It's obvious nothing that can't be done manually, it
would just be a nice to have. Maybe a flag that shows documents that are
suspected to be rotated or corrupted (OCR-wise)? One might be able to
implement that by checking the % of words that actually make sense (and are
actually words) versus overall word count in the document.

Not a necessity by any means.

**Comment by jonaswinkler** [comment]
Rather than doing this, I'd eventually like to use the auto rotate feature of the OCR software I'm using in paperless.

https://ocrmypdf.readthedocs.io/en/latest/cookbook.html#correct-page-rotation

I just need to make sure that this is compatible with all existing configuration options.

**Comment by jonaswinkler** [comment]
I'm just moving the discussion of many related issues into one new issue.

**Comment by Patricol** [comment]
IMO there should still be a way to override an incorrect rotation judgement in the frontend; even if it isn't in-place. Of course it can be made more or less sensitive; but that isn't magic; there is no sweet spot where everything will work.

The backend procedure does indeed sound onerous, but making people export, delete, rotate, reupload, retag, etc. themselves doesn't sound like the long-term ideal way. I think the issue should remain open in case someone interested enough to implement it comes along.

**Comment by ark-** [comment]
This would be useful as sometimes the PDF conversion gets it wrong and the OCR output is therefore fairly useless. Could fit nicely into the UI from #335
