### ISSUE TITLE
Error consuming pdf

### ISSUE THREAD

**Issue by andbez** [jonaswinkler/paperless-ng#291]
Setup: paperless-ng  0.9.11

Following error occurs with every single file, when paperless tries to consume:
08:06:27 [Q] ERROR Failed [2007-08-07 - Rechnung - Alice.pdf] - Unsupported mime type application/octet-stream of file 2007-08-07 - Rechnung - Alice.pdf : Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django_q/cluster.py", line 436, in worker
    res = f(*task["args"], **task["kwargs"])
  File "/usr/src/paperless/src/documents/tasks.py", line 73, in consume_file
    override_tag_ids=override_tag_ids)
  File "/usr/src/paperless/src/documents/consumer.py", line 109, in try_consume_file
    f"Unsupported mime type {mime_type} of file {self.filename}")
documents.consumer.ConsumerError: Unsupported mime type application/octet-stream of file 2007-08-07 - Rechnung - Alice.pdf

And the file will not be consumed into paperless.
 It seems, the file is the problem.... but i can view the file and its content in my pdf-Viewer.

**Comment by jonaswinkler** [comment]
Paperless uses mime type checking tools to verify that files are actually what they pretent to be.

Run `file --mime-type document.pdf` to see what it is. If it reports "application/pdf", its a known issue of paperless (older dependencies that don't recognize this file). If it's reporting "application/octet-stream", then it's the PDF that's the issue. Even if I where to remove the mime type checks, the OCR library itself would also complain about the file not being a proper PDF document.

In any case, something is wrong with this file, and that's why paperless is rejecting it. PDF is a pretty wild and complex format, and many PDF viewers have workarounds for documents that don't adhere to the PDF specification.

See also #201. This issue reports the same problem. I've got it on the radar.

The intended fix is to update binary dependencies of paperless (which is something I want to do anyway, the newer versions of the OCR libraries have some important changes), but that will cause issues with Raspberry Pi compatibility; I need to figure this out first.

In the meantime, users have reported that saving problematic PDF documents with a PDF viewer allowed them to import these into paperless.
