### ISSUE TITLE
Possibility to select a subset from search results and perform collective changes

### ISSUE THREAD

**Issue by michilge** [jonaswinkler/paperless-ng#357]
Search results are currently displayed on a page from which only single matching documents can be opened for editing.
It would be helpful if multiple matches could be selected to perform a bulk edit on the selection.

Regards, compliments and best wishes included.
Stay safe

**Comment by Philmo67** [comment]
Also "include/exclude" logic could be great while selecting tags filters. 
To go further, the view settings logics available in the "administration" section could be interesting everywhere (and/or/not equivalents).

**Comment by jonaswinkler** [comment]
> Also "include/exclude" logic could be great while selecting tags filters.

This is a different topic, please open a new feature request for that. This here is about full text search.

> To go further, the view settings logics available in the "administration" section could be interesting everywhere (and/or/not equivalents).

Which settings exactly? The "Saved View" settings are just the way paperless stores filters in the database. I'm not exactly sure what you mean by and/or/not equivalents.

> Search results are currently displayed on a page from which only single matching documents can be opened for editing.
> It would be helpful if multiple matches could be selected to perform a bulk edit on the selection.
> 
> Regards, compliments and best wishes included.
> Stay safe

When I started this project, I decided to keep the search results and the document list views as two separate things, because:
- The full text search should be a feature to find that one document you're looking for
- The document list should be a feature to edit and manage lots of documents

While that might have not been the best decision, this is what we have right now. I tried to make full text search available with the document list as well, but this is VERY difficult due to how differently both features work under the hood, see here: https://github.com/jonaswinkler/paperless-ng/issues/217#issuecomment-752670218.

The bulk edit and filtering tools only work with the document list, which leaves us with the following options and associated problems:

1. Add bulk edit (and possibly filtering) to the search results, which is pretty hard; the components were created to only work with the document list, and not the search results.
2. Unify these two features, however, see the notes above.

I'd really like to have this myself, but it won't happen anytime soon, unfortunately.

**Comment by abctje** [comment]
This would be a great addition to Paperless! It could save a lot of work when processing al lot of documents.

**Comment by jonaswinkler** [comment]
Got this mostly working now. Full text search results and more like this results will use the standard document list, including all features such as filtering, sorting, bulk editing, and saved views. Still got quite a couple minor annoyances to address.

**Comment by michilge** [comment]
Hi,
I just got the update. This works just like I had imagined. It will save a lot of clicks. In combination with the dropdown allowing to select all matches, all documents on the current page or to remove all selctions this is a great improvement.
Thanks a lot!

**Comment by jonaswinkler** [comment]
All searching functionality will now use the default document list and will work with filtering tools, selection and bulk edit.
