### ISSUE TITLE
The correspondent field in the title of the result is no clickable filter when using the full-text search

### ISSUE THREAD

**Issue by Tooa** [jonaswinkler/paperless-ng#369]
When using the full-text search the correspondent field in the result view is no clickable filter (same for the tag). Would be nice if this could be streamlined hence the document view let me click on the correspondent (tag). Let me know if you need more information.

Version: 0.9.14 (Docker installation)

**Comment by jonaswinkler** [comment]
What should happen when you click on the tag or the correspondent? Drill down the search results to just this correspondent or tag?

**Comment by Tooa** [comment]
> What should happen when you click on the tag or the correspondent? Drill down the search results to just this correspondent or tag?

I thought about showing **all** documents with this tag or correspondent. Not sure if drilling down the search would be useful. However on the other hand it might be confusing to retrieve all documents associated with the tag or correspondent after using the full-text search.

Anyway I was asking for  **all** documents with this tag or correspondent. What do you think?

**Comment by shamoon** [comment]
Makes sense to me, I have been in that situation with tags on search results. Look for a doc -> want to browse others with same tag (or in this persons case, Correspondent). I think would work if it took you to the document list?

I had been meaning to look at this but wasnt sure how we could directly navigate to tag/corresp/dt since filters dont change URL...

**Comment by jonaswinkler** [comment]
When clicking tags or correspondents on the document list, the current behavior is to add (or remove) that tag or correspondent to/from the current filter set. This will only show all documents with this tag or correspondent, if there were no filters applied before. In all other cases, the list is reduced to documents shown before, limited to documents with that specific tag or correspondent.

Since the search results are pretty similar in terms of layout to the document list when using large cards, I thought that clicking these elements should do something similar to what they do on the document list.

Navigating to the document list with filters is easy, just look at the management pages and the "Documents" buttons.

**Comment by shamoon** [comment]
I think we’re saying the same thing, cards are same as document list so I think users might expect they can click a correspondent / tag just like they can in document list. From search results to me at least would make sense that clicking an item would take you to document list with that item selected. I just meant technically wasn’t sure how to “deep link” to a tag/corresp/dt

**Comment by shamoon** [comment]
Ie if we do it with query params I’d feel obligated to fully implement them for the filter editor (uh oh, should we??)

**Comment by jonaswinkler** [comment]
No query parameters.
