### ISSUE TITLE
Make an Android app that allows you to share any documents on your mobile with paperless.

### ISSUE THREAD

**Issue by jonaswinkler** [jonaswinkler/paperless-ng#37]
Essentially allowing consumption with any of these mobile scanner apps.

**Comment by jonaswinkler** [comment]
This is reasonably simple, since all the app has to do is to provide an interface to enter credentials, store them, and then provide a "Share with paperless" target that uploads a given file to an API endpoint. Perfect integration with any mobile scanner a

**Comment by qcasey** [comment]
I made a flutter app that serves this purpose and has been working for me. Will publish in a bit, but any particular reason this was closed?

**Comment by jonaswinkler** [comment]
Oh, well, that sounds great!

I've just decided that I don't have the time or knowledge to do this myself. If you publish something, please let me know, I'd like to try that out.

**Comment by qcasey** [comment]
Thanks, I'd like to get your input. It's a little rough around the edges but has been working for me for a few days now:

https://github.com/qcasey/paperless_share

> Btw, if you need anything more from the API, lets say token authentication or post_document form fields for assigning tags and correspondents, I can make that happen.

That would be ideal, the password is stored in basically plain text. Maybe tags/correspondents for the roadmap? Sounds cool.

It would probably make more sense to implement this entire app as PR to [paperless_app](https://github.com/bauerj/paperless_app) instead of using two separate ones. Especially since they're both written in flutter. I can't get theirs to work with your fork though. 

I personally just upload on mobile so I'll stick with mine for the time being :)

**Comment by jonaswinkler** [comment]
This is awesome. Even with just the camera app and sub-par lighting, tesseract is still able to detect text. And the new version of paperless makes that text selectable. I love it.

I think with these specialized 'scanner' apps that trim and improve contrast, you can get some pretty good results. 

If we can get this into one app, it would be even better. I'm ironing out the api and making things final right now so.

**Comment by qcasey** [comment]
Thank you! Yes I've also been really impressed with the OCR on phone camera scans. 

Looks like there's some movement over at paperless_app compatibility -- glad to see it. In the meantime I've submitted this Share app to Google Play and FDroid. 

Let me know once you think the API is mostly set, I'll make the necessary changes.

**Comment by jonaswinkler** [comment]
The API is now mostly set and I won't make any changes to the existing endpoints anymore, except for the /search endpoint. This one might see some changes.

However, I'm also looking into versioning the API, so that older API endpoints are still available.

**Comment by qcasey** [comment]
Nice, thank you! I'll make those updates in time.

I suppose we can close this issue now if you'd like.
