### ISSUE TITLE
Use existing folder structure

### ISSUE THREAD

**Issue by spacemanspiff2007** [jonaswinkler/paperless-ng#412]
I am interested in using paperless-ng, however I already have a existing folder structure in place where I organize everything.
Additionally to documents I keep other correlating data there so it is not easily possible to get rid of the existing structure.
I am also hesitant to dump everything into paperless-ng because getting all my documents out of it seems to be messy.

Would it be possible to specify a (read only) folder that just gets indexed e.g. every day or so?

**Comment by jonaswinkler** [comment]
No, this is not possible right now.

**Comment by spacemanspiff2007** [comment]
I am aware that this is not possible right now. 
What I am asking is wether it will be possible some time and if you are interested in making or accepting a change that changes the file behavior accordingly.
Imho the database and all the logic should be independent of the file structure anyway but I don't know the internals and I could be that there was a deliberate decision for this.

**Comment by jonaswinkler** [comment]
Unlikely. This would be a very big change.

* Paperless assumes that no one else modifies the media directory. Everything is built around that assumption.
* Paperless assumes that all documents are stored in the media directory.
* Paperless stores filenames for all documents to associate files in the media directory with documents in paperless.
* Paperless stores checksums of all files.
* Paperless manages filenames and renames files according to metadata, if configured.

Assume we would allow paperless to use existing folder structures (=allow external changes to the media directory), apart from having to write logic that detects changes in the media directory and updates documents in paperless (=updated content), we have to deal with the following issues:

* Paperless uses checksums to verify file integrity. With external changes, we can't discriminate between intentional changes to files and damage due to file system errors, bad backup restores, etc.
* How do we find the files for a document if you decide to move it somewhere else? This should not be a new document, because you'd likely want the tags / correspondent / etc to carry over to the moved file.

If you really need this, you should probably look for a different tool.

**Comment by spacemanspiff2007** [comment]
My intention is not to nag but rather provide constructive feedback and ideas so please don't get me wrong.


>     * Paperless stores filenames for all documents to associate files in the media directory with documents in paperless.

Imho this matching documents should be based on the hash and not the file name. That way the association is independent of the folder/file structure and even works if the user moves the files around. The disk path should only be another entry in the db (as it is).
This would solve your mentioned issues, except for the file corruption. However since you are likely trying to serve the file to the user and process it anyway I don't think there is too much benefit to highlight that the file is/might be corrupt.

The workflow then would be easy:
Scan all provided folders and skip hashes that are already in db. Process files that are not yet in db and add them by file hash.
Clean files that don't exist any more.

The nice thing is that this would also work on the input folder so there would not be too code branches. The only thing different for the input folder would be a "move files away from here" flag that moves the file after processing.

Everything else would work as usual.
