### ISSUE TITLE
Alter filename by extracted metadata

### ISSUE THREAD

**Issue by Matthias84** [jonaswinkler/paperless-ng#427]
Hi, I usually add documents, which have just numbers / timestamp as filename and aren't easy to distinguish. Would it be possible, to add an option, where the filename of new files can be prefixed / suffixed if the consumer was able to extract metadata as documenttype / contact / tags / ... ?

**Comment by shamoon** [comment]
Exporter has this see https://github.com/jonaswinkler/paperless-ng/issues/166

**Comment by jonaswinkler** [comment]
If you're referring to adjusting the filename in the media directory based on metadata, look up `PAPERLESS_FILENAME_FORMAT`.

If you're suggesting adding the correspondent name, type, or tags to the title of the document (as displayed in the web UI): That won't happen, since it is redundant to have that information both assigned to a document as well as in the title.
