### ISSUE TITLE
Show multipage documents within lists

### ISSUE THREAD

**Issue by Matthias84** [jonaswinkler/paperless-ng#433]
Currently we don't show if a document has muliple pages, as we only show first page in thumbnails
We might represent it with a stack of paper, or a watermark / page counter label?

**Comment by shamoon** [comment]
Sure, but why?

**Comment by C0nsultant** [comment]
The document thumbnail/preview system in general could use a few tweaks.
I have quite a few documents that are not very tall and rather wide. They have text aligned on the left and text aligned on the right, text in the middle is mostly there by coincidence. Because the preview generation zooms in to at least a certain pixel height, the square preview is often just a mostly blank box:
![Screenshot from 2021-01-24 20-28-51](https://user-images.githubusercontent.com/10155170/105641142-ccd1e800-5e82-11eb-9c87-0b90889b2286.png)
That approach works well when all of your documents are single-page DIN or letterbox, *letter-style* portait layout. I guess the idea originates from real-life experiences of sifting through stacks of multi-page documents.

**Comment by shamoon** [comment]
@C0nsultant A separate issue isnt it?

**Comment by C0nsultant** [comment]
Depends on what GH issues are supposed to be. If you want a pure bug-tracking system, sure. I would like to have a discussion without spamming new issues that just pile up, and then get closed with single-word responses.
Suggesting one change to a system should not mean all other opionions regarding that systems should have to be separated... as is the case with the document preview is this case.

**Comment by jonaswinkler** [comment]
I might have to create issue templates or something. So far, tagging issues and assinging them to milestones is okay for keeping things organized for myself.

> Suggesting one change to a system should not mean all other opionions regarding that systems should have to be separated... as is the case with the document previews here.

True.

**Comment by shamoon** [comment]
> I might have to create issue templates or something.

Was in the process of suggesting this. I dont think it will make a huge difference but its a place to remind people to search to prevent duplicate issues, perhaps encourage some more trial & error, etc. and for bug reports helpful to get more info.


> Suggesting one change to a system should not mean all other opionions regarding that systems should have to be separated... as is the case with the document previews here.

Yes of course agreed I just meant that OP here was a rather specific issue to begin with as is yours which I would say is closer to a bug and this issue is more of a feature request. Obviously not a big deal, and yes, tons of tiny "issues" is not great either but for example we're now discussing two fairly distinct issues which can get confusing both in conversation and when tagging PRs etc

Aaaanyway, @C0nsultant your issue is just basically wide documents are cut off in a weird way in the thumbnail, yes?

**Comment by shamoon** [comment]
@C0nsultant I just tested with a [sample pdf](https://github.com/jonaswinkler/paperless-ng/files/5863335/2021-01-20.sample_wideo.pdf) that I made very wide, this is resultant thumbnail which obviously there is some blank space because the card is portrait and the image is landscape but this seems pretty reasonable to me. Are you seeing something different and if so can you provide a test file?

<img width="216" alt="Screen Shot 2021-01-24 at 2 24 42 PM" src="https://user-images.githubusercontent.com/4887959/105645692-2ec52a00-5e50-11eb-9979-0a44fda14e77.png">

**Comment by Matthias84** [comment]
> Sure, but why?

To get remembered, that there are some more pages. Somtimes I look at the thumbnail and get confused, because I missed a particular sheet of paper e.g. with a table etc. and forget, that this is just the next page on the document.

**Comment by jonaswinkler** [comment]
> The document thumbnail/preview system in general could use a few tweaks.
> I have quite a few documents that are not very tall and rather wide. They have text aligned on the left and text aligned on the right, text in the middle is mostly there by coincidence. Because the preview generation zooms in to at least a certain pixel height, the square preview is often just a mostly blank box:
> ![Screenshot from 2021-01-24 20-28-51](https://user-images.githubusercontent.com/10155170/105641142-ccd1e800-5e82-11eb-9c87-0b90889b2286.png)
> That approach works well when all of your documents are single-page DIN or letterbox, _letter-style_ portait layout. I guess the idea originates from real-life experiences of sifting through stacks of multi-page documents. But that should not mean we do not think outside this box.

I've tried to make that a little better by always showing the top left corner of the thumbnail, instead of centering it.
