### ISSUE TITLE
Bare metal web server issue

### ISSUE THREAD

**Issue by Engr-AllanG** [jonaswinkler/paperless-ng#444]
Hi, I've been running paperless-ng on docker for a few weeks - great app!

Docker doesn't make sense for my setup so I am setting it up with the bare metal installation guide in an ubuntu 20.04 container on proxmox. I successfully started the development server and logged in. Now I'm trying to setup the services with systemd. I copied over the scripts and edited them. The consumer and scheduler run fine, but the webserver.service has a command that doesn't look right. First, after modifiying the path to my installation folder (/root/paperless-ng) the .local and beyond file path doesn't exist. I looked through the code on github and also don't see a paperless.wsgi file exists. Furthermore, I assume I have to install gunicorn as well?

`/root/paperless-ng/.local/bin/gunicorn paperless.wsgi -w 2 -b 0.0.0.0:8000`

Any input on this would be helpful, thanks!

**Comment by Engr-AllanG** [comment]
I decided to simply try using the command `python3 manage.py runserver 0.0.0.0:8000` in the systemd file and it worked fine. Is there a reason not to do that? I don't know why its considered a development server.

Thanks

**Comment by jonaswinkler** [comment]
It is a development server, because:
* The web server reloads when the sources change.
* It's not optimized for concurrent acccess at all (might not be an issue here)
* No security fixes.

`gunicorn` is installed as part of the python dependencies. The actual location depends on whether you created a virtual environment and where that is. The look for the .local directory in your home directory if you did not use virtual environments, or look for gunicorn inside the bin folder of your virtual environment.

paperless.wsgi is not a file, but the module name of the wsgi application (src/paperless/wsgi.py).

**Comment by MZorzy** [comment]
i had changed paperless-webserver.service to
"ExexStart=python3 /opt/paperless/src/manage.py runserver 0.0.0.0:8000"

now can confirm that after "cd /opt/paperless/src"
doing 
"/usr/local/bin/gunicorn paperless.wsgi -w 2 -b 0.0.0.0:8000"
is working, so will rechange service :+1:

**Comment by Engr-AllanG** [comment]
@jonaswinkler thank you very much! Your explanations helped a lot.

I found it in `/usr/bin`. Now its up and running

**Comment by jonaswinkler** [comment]
I'll close this after making the necessary documentation changes.
