### ISSUE TITLE
[BUG] Changes in "Content" tab are not applied to PDF

### ISSUE THREAD

**Issue by rYR79435** [jonaswinkler/paperless-ng#502]
When I edit a document and make changes in the "Content" tab (the OCR'd text), these changes are not applied to the PDF. The changes are being saved, since I can see them in the "Content" tab, after having saved and reopend the document. But when I open the document in my browser, I cannot search for my changes. (I have verified that searching for successfully OCR'd passages works)

I expected to be able to change the OCR'd text like this because I can edit and save it (something I cannot do in the "Metadata" tab).

**Comment by jonaswinkler** [comment]
Unfortunately, that's not how this works. I cannot add the edited text from the content field to a PDF document.

* What if a user adds lots of notes and keywords (some do that, since the content field is searchable) to the content field, where should I place that on the PDF document?
* What if you add some words to a sentence? The text layer won't match with the image layer anymore. Scanned documents consist of an image with an invisible text layer on top.

I've also considered to not include the content field at all when building the front end, since it's not really supposed to be edited anyway. But I guess it's useful to verify OCR quality, for copy / pasting, and apparently for note taking as well.

I'll probably never support changing anything on original documents. It's certainly possible and not hard to do, I just don't want the software to be responsible for any kind of data loss should that editing fail (silently).

**Comment by rYR79435** [comment]
I see.

I suggest the edit functinality is slightly altered then.
I think it would make sense to have the OCR'd text be not editable (like the metadata).
And, since thats apparently a yearned for function, a "Notes" tab.

This would avoid confusion IMO.

**Comment by jonaswinkler** [comment]
Notes will come as part of #274, but that's a pretty big task.
