### ISSUE TITLE
[Other] export task in Django Q scheduler

### ISSUE THREAD

**Issue by igno2k** [jonaswinkler/paperless-ng#508]
I would like to schedule the backup with the builtin scheduler. Is there a function for this or anynone knows how to add it?

If I click on "Add" I have to enter a function name. Maybe this could also be a good addition for others in the documentation :)

**Comment by jonaswinkler** [comment]
Hello!

This is certainly possible, but I don't exactly want to advertise this as a feature, since it's very easy to not get the syntax right. This could be potentially dangerous.

Here's how you do it.

1. Specify a name, such as `Daily export`.
2. Specify the function `django.core.management.call_command`.
3. Specify Args: `('document_exporter', '../export')`. With brackets and single quotes. Note that this has to include a comma even if only one argument is specified.
4. Specify Kwargs: `{}`. This is important.
5. Specify a schedule.
