### ISSUE TITLE
[BUG] Not consuming some documents - died with <Signals.SIGKILL: 9>

### ISSUE THREAD

**Issue by luiscachog** [jonaswinkler/paperless-ng#550]
**Describe the bug**

On a docker installation, I'm receiving the following error:

[2021-02-14 20:40:15,083] [ERROR] [paperless.consumer] Error while consuming document ckad-certificate.pdf: CalledProcessError: Command '['unpaper', '-v', '--dpi', '400.0', '--layout', 'none', '--mask-scan-size', '100', '--no-border-align', '--no-mask-center', '--no-grayfilter', '--no-blackfilter', '--no-deskew', '/tmp/tmp47tblu3g/input.pnm', '/tmp/tmp47tblu3g/output.ppm']' died with <Signals.SIGKILL: 9>.

Not sure how to debug the issue.

**To Reproduce**
1. Move the document to a consumer folder
2. Wait until the consumer starts 
3. Wait for the error

**Expected behavior**

The consumer adds the document to paperless-ng

**Screenshots**
Issue not in the UI

**Webserver logs**
```
[2021-02-14 20:40:15,083] [ERROR] [paperless.consumer] Error while consuming document ckad-certificate.pdf: CalledProcessError: Command '['unpaper', '-v', '--dpi', '400.0', '--layout', 'none', '--mask-scan-size', '100', '--no-border-align', '--no-mask-center', '--no-grayfilter', '--no-blackfilter', '--no-deskew', '/tmp/tmp47tblu3g/input.pnm', '/tmp/tmp47tblu3g/output.ppm']' died with <Signals.SIGKILL: 9>.```

**Relevant information**
 - Host OS of the machine running paperless: MacOS/Docker
 - Browser: Chrome
 - Version: 1.1.2
 - Installation method: docker
 - Any configuration changes you made in `docker-compose.yml`, `docker-compose.env` or `paperless.conf`.

**Comment by jonaswinkler** [comment]
Does the error repeat when you add that document again?

This is probably an error that happens somewhere between `ocrmypdf` (The library that's responsible for performing OCR), and `unpaper` (a program that increases image contrast and other things for better OCR results, called by `ocrmypdf`).

The only thing I could do is forward this to the appropriate repository, but they'd also need the actual file to do anything.

**Comment by luiscachog** [comment]
Hello @jonaswinkler!!

If this [https://ocrmypdf.readthedocs.io/en/latest/release_notes.html](https://ocrmypdf.readthedocs.io/en/latest/release_notes.html) is the correct repository, they suggested to upgrade versions [https://github.com/jbarlow83/OCRmyPDF/issues/575](https://github.com/jbarlow83/OCRmyPDF/issues/575).

I do see that your image is running version `11.6.0`.

```
ocrmypdf --version
11.6.0
```

There are 2 new minor versions available, that probably will fix the issue. Are you planning to update `ocrmypdf` soon?

**Comment by jonaswinkler** [comment]
Sure, I do update dependencies regularly.

However, after scanning through the referenced issue, tesseract is at fault for this issue, so upgrading ocrmypdf wont help. See also #48. This boils down to this:

* In order to support ARM hardware, I need python 3.7. Only this version of python has precompiled binaries available for ARM which otherwise take ages to build.
* There is no debian / ubuntu base image with both python 3.7 and tesseract 4.1.1 available.
* I don't feel very stoked about mix-matching packages from both debian stable and debian testing. This will also increase the image size by *quite a lot*.

I don't plan to drop support for ARM, so we're at an impasse here until newer versions of python get better ARM support.
