### ISSUE TITLE
[Feature] Filter documents by title and content

### ISSUE THREAD

**Issue by jonaswinkler** [jonaswinkler/paperless-ng#636]
In version 1.2.0 I'm able to do a fulltext (content) search in the top (green bar).
Output is a list of all documents found, with probability, but features from documents section filtering are missing (select, add tag, bulk download...)

What I would like to have is the options of the filtering under documents.

-select found documents
-add tag, correspondant,.. to selection
-or download all selected files as .zip
-change views

I don't know what is best?

a) add the features from the document filter to the search in the top
b) add context search to the document section

Plus:
It would be nice to have a option for the document retagger to specify which tag to work on (not use all tags).
#mamage.py document_retagger -T 'tagstring'

Regards

_Originally posted by @nrygh in https://github.com/jonaswinkler/paperless-ng/discussions/614_

**Comment by shamoon** [comment]
Saw this in dev, its great. LMK what you think about this visual tweak, small checkboxes instead of dropdown:

<img width="733" alt="Screen Shot 2021-03-03 at 10 18 57 PM" src="https://user-images.githubusercontent.com/4887959/109920744-981a3300-7c6f-11eb-83a1-9e23a42e5b86.png">
<img width="730" alt="Screen Shot 2021-03-03 at 10 19 22 PM" src="https://user-images.githubusercontent.com/4887959/109920746-98b2c980-7c6f-11eb-9097-5011f62aeec6.png">

Would need some changes to the logic too. Just a thought!

**Comment by jonaswinkler** [comment]
Good idea, but: 

This dropdown will eventually also have an option to use the provided text filter for full text searching (I'm working on integrating that). Read: Sorted and highlighted query results, but with the added ability to filter and bulk-edit. This might replace "title & content", so I'd like to stay this the way it is right now.

**Comment by shamoon** [comment]
Gotcha yea sounds like a big change, we can circle back after that
