### ISSUE TITLE
Paperless skipping Inline Attachments

### ISSUE THREAD

**Issue by soberhofer** [jonaswinkler/paperless-ng#70]
Hi there, 

when attaching a pdf on Apple Mail on macOS apparently the document is attached differently than on some other clients. 

here is an excerpt of the Mail:

```
--Apple-Mail=_C1D774F2-9286-4AF1-B39A-F21DDFCFB36A
Content-Disposition: inline;
	filename=REDACTED.pdf
Content-Type: application/pdf;
	x-unix-mode=0644;
	name="REDACTED.pdf"
Content-Transfer-Encoding: base64
```

If I attach the document via WebMail it looks like this

```
--=_cc354e7e2097e4e73a8e0855eb690035
Content-Transfer-Encoding: base64
Content-Type: application/pdf;
 name=REDACTED.pdf
Content-Disposition: attachment;
 filename=REDACTED.pdf;
 size=41600
```

If the attachment is "inline" i get the following line in the debug log of Paperless-ng:

` 11/29/20, 4:19 PM DEBUG Rule REDACTED.ALL: Skipping attachment REDACTED.pdf with content disposition inline `

Is there a reason for skipping inline attachments?

Thanks

**Comment by jonaswinkler** [comment]
The reason is, that many html mails like to embed images in their mails, and they do that as inline attachments. Since paperless accepts both PNG and JPG as documents and adds them to its database, this check was put in place.

Example. I get mails from my internet provider. Some contain Invoices as attached pdf documents, some contain advertisement as inlined images.

Adding an override for this is easy, but you need to be aware of that.

**Comment by soberhofer** [comment]
Makes sense, i have found there is an option to "add attachments at the end of message" which makes them a "proper" attachment. This should solve it. Maybe an override would make sense as a config option in the mail rules for some edge cases.
Thanks

**Comment by totti4ever** [comment]
@soberhofer, does it really work that way for you? I tried it exactly as you described (also on Mail @ macOS) and paperless still says it's inline :-(
