### ISSUE TITLE
Improvements when working with filters

### ISSUE THREAD

**Issue by totti4ever** [jonaswinkler/paperless-ng#79]
Hey, I hope it's okay if I keep on dropping things which come to my mind when working with this excellent piece of software (seriously! :-) )...just keep the ones you agree with:

1. If there are filters set and you leave the site, go somewhere else and come back, the filters are still set (as expected), but hidden - this is quite irritating as you cannot see straight away that the results are filtered

1. Am I understanding it right that the global search box does not work together with the filters? I guess this is by concept?
	1. It is a bit irritating when I have set some filters and then want to search inside those results. I know that I have to add a filter for _title contains_ or _content contains_ now
	1. The other way around, it would be great to filter the results of a fulltext search further down

1. Do you have any influence on the order of the suggestions? I find it quite irritating as well when the word I wrote is not the one being selected when hitting enter: <br /><img src="https://user-images.githubusercontent.com/49901208/100800155-761dd400-3426-11eb-947b-1701d3b9133e.png" height=105 />

1. Show the number of search results also for a filter-search (already shown for a fulltext-search)

1. I missed the filter _Does NOT have tag ..._  
Is nice to validate combinations, but also to clean dashboard lists (like show all docs, but not manuals). So it might be nice to have a general NOT switch for filters

1. Would it be possible to create a word cloud from the fulltext-search suggestions? I would love to see which words appear most often in my documents! :-D  
of course, this is a gimmick...

**Comment by jonaswinkler** [comment]
1. Easy fix, agree. Noted.
2. Global search is for quickly finding one particular document you're looking for, Filtering is for editing and managing large amounts of documents. It's by design. The title/content contains filters aren't even intended to be used for specific searching, rather for identifying a group of documents you can't identify with the other filters. The search box searches everywhere, simultaneously, and brings up on top whatever matches the query best.
3. I do. They are sorted by importance in your document collection. Lets say you have one document with the word "theology" and many documents with the word "the", typing "the" will then bring up "theology" first. I agree that bringing the word you typed up first might be better.
4. I see. Noted.
5. Have to check with the filter API. Might be easy, might be very hard.
6. Some day, someone will come up with making a customizable dashboard. I.e., dragging boxes between columns, and adding/removing them freely. Then we can start implementing fancy stuff that some/some more users might not want on their front page.

**Comment by jonaswinkler** [comment]
1 and 4 are done. 5 is on the list.
