### ISSUE TITLE
Allow setting metadata when uploading document through REST API

### ISSUE THREAD

**Issue by bauerj** [jonaswinkler/paperless-ng#81]
The API currently provides an endpoint [`/api/documents/post_document/`](https://paperless-ng.readthedocs.io/en/latest/api.html?highlight=upload#posting-documents) for uploading documents.

Since it takes the usual route through the consumer directory, metadata may only be set through the file name.

There are some drawbacks to this:

- It's unnecessarily complicated from the client point of view
- Correspondents can only be referenced by name not ID
- Some file systems do not support the full character set which may lead to encoding issues
- The format (Date - Correspondent - Title - tag,tag,tag.pdf) does not allow arbitrary titles or correspondent names (how would "20150314000700Z - Company - Berlin Branch - Inventory - List - inventory.pdf" be parsed?)

If it's not too complicated on the server side it would make sense to allow setting these as form values or through a JSON body in the POST request.

**Comment by jonaswinkler** [comment]
> Since it takes the usual route through the consumer directory, metadata may only be set through the file name.

That is no longer true. Uploads go to a temporary directory and the consumption logic is then pointed towards that file to process it. It is not dependent on the directory monitoring at all.

Furthermore, the consumption logic already has parameters that allow us to override titles, correspondents, and types, and specify additional tags, all by ID. This was required for the mail client.

So this is rather easy. However, would you like to be able to
- set correspondents / tags / types by ID, and receive errors when they are not found
- set correspondents / tags / types by name, since that's also unique, and have paperless automatically create missing objects. This would still allow clients to select data from lists.

**Comment by bauerj** [comment]
Oh cool. I haven't had a chance to look at all the changes yet.

In this case, I would prefer using IDs. While names are unique as well, the app may not always have the same state as the server.

**Comment by jonaswinkler** [comment]
Names might change, IDs stay the same, I figure that's what you're referring to.

Fair enough, that's even simpler then.

**Comment by jonaswinkler** [comment]
Done, its in the latest release.
