### ISSUE TITLE
Save sorting as default view?

### ISSUE THREAD

**Issue by silembir** [jonaswinkler/paperless-ng#824]
Hello, 

I know that I can create default views with documents sorted a specific way but is there a way to make a new view the default?  I like to have my documents sorted by recently added and the default view is recently created.  Thanks.

**Comment by git-help-eng** [comment]
Hello,
    I can try to help you clarify what you are trying to achieve.  I'm not sure what you mean by 'default view'.  For me when I click on the Documents menu item in the upper left corner:

![Views](https://user-images.githubusercontent.com/79425928/112911860-43c66f80-90c4-11eb-8aba-fea19abb5d8b.png)

the last way that I configured that view is saved.  So if I wanted to have it sorted by added date (instead of created date) then I would specify that in the Sort dropdown and then that would be the way that that view would be sorted until I manually selected some other sort order from the dropdown.

If you are refering to the sorting of a view that you have manually created and chosen to show on the dashboard then you should be able to specify the sort order for that view in a similiar manner.  First select the view, then specify the order from the Sort menu, and then save the view from the Views menu.

**Comment by jonaswinkler** [comment]
I've changed the behavior so that the list view will remember its last settings between browsing sessions.
