### ISSUE TITLE
Do you use the filename guesswork feature?

### ISSUE THREAD

**Issue by jonaswinkler** [jonaswinkler/paperless-ng#83]
You can name files in certain ways and paperless will pick up metadata from that, such as tags, dates and titles.

See guesswork in the documentation.

Do you use it?

**Comment by brianwanderson** [comment]
Hi,

Here is some feedback on how I use paperless:

I really like the  PAPERLESS_FILENAME_DATE_ORDER=<format> setting in the config file.  I prefix all of my documents with YYYY.MM.DD so that I end up with file names like: "2020.12.01 - Document Title.pdf".  That way, I can always sort my documents chronologically in a file browser.  It's really convenient that paperless will automatically set the documents date from the file name on import.

Beyond grabbing the date, I don't use any of the filename guesswork features.  Personally, I think anything more is overkill.  I don't want to be bothered by having to remember some special file name format like "Correspondent - Title - tag,tag,tag.pdf"    It's easier for me to name my files however I wish and to assign correspondents and tags in the GUI after import.

**Comment by qcasey** [comment]
Basically the same here, I'd see myself using filename guesswork on dates when bulk importing a bunch of documents. Paperless has been very good at filling in titles and dates otherwise. 

I personally don't use correspondents or tags at all. The search function is really good enough.

**Comment by rssfed23** [comment]
Personally no, as my scanner gives random filenames and going through and renaming would be more effort when the existing search and auto tagging capabilities are so good 👍
