### ISSUE TITLE
Feature requests and feedback from a user's perspective

### ISSUE THREAD

**Issue by brianwanderson** [jonaswinkler/paperless-ng#88]
Hi Jonas,

I'm writing this post to provide my feedback on paperless-ng.

First, a little background:  I consider myself a database guru, but a mere enthusiast/tinker when it comes to coding python.  I used Mayan (https://mayan-edms.com) to organize my home office documents for many years, but found it to be too cumbersome and overly complex for my needs.  One thing it did do, however, is force me to think about how to organize my scanned documents in a way that makes sense to me.  I've recently pulled all of my documents (~1500) out of Mayan and now store them in a simple file system hierarchy.  I went searching for a new tool and found my way to your project, and all I can say is, thank-you.  Great work on a great project.  It checks all the right boxes for me: keeps it simple, OCRs documents and provides robust searching, stores the documents in the file system in a hierarchical way of my choosing, uses SQLite for simple backups or PostgreSQL (yeah!!) for larger setups, runs in a browser, is written in Python, has an intuitive GUI.

I'm following the development with great interest.  For what it's worth, here is my list of feature requests and, perhaps, points of discussion:

#### 1. Add a placeholder for document type to PAPERLESS_FILENAME_FORMAT

Such that if document types = Auto, Finance-Banking, Insurance-Health
and
```
PAPERLESS_FILENAME_FORMAT={document_type}/{correspondent}/{title}
```
I end up with something like:
```
Auto/
  /Joes_Auto_Repair
    2018.12.01-car_repair_bill-0000001.pdf
  /My_Local_Tire_Shop
    2020.08.01-new_tires_invoice-0000002.pdf
Finance-Banking/
  my_bank/
    2019.07.31-statement-0000003.pdf
Insurance-Health/
  my_insurance_company
    2020.08.31-benefits_statement-0000004.pdf
```

#### 2. Don't alter the filename.
Currently, when the file is stored in the media directory, the filename is changed to all lower case, no spaces, and the document ID is appended on the end.  For example, if I were to do the following:

1. import: "2020.12.01 Bank of America - Statement.pdf"
2. set the correspondent to "Bank of America"
3. set:
```
PAPERLESS_FILENAME_FORMAT={correspondent}/{title}
```
the file gets stored in the media directory as:
```
/path-to-media/documents/originals/bank-of-america/20201201-bank-of-america-statement-0000056.pdf
```
But, I would like it to be:
```
/path-to-media/documents/originals/Bank of America/2020.12.01 Bank of America - Statement.pdf
```
I would argue the following: 
1. It's the database's job to uniquely identify a file (it's ID number in this case), and to keep track of where the file is located in the file system.  Removing spaces and capital letters and appending the document ID to the end of the filename is unnecessary and inconvenient to the end-user.  
2. Having duplicate titles/filenames would be an error on my part that I want to know about.  Trying to name two documents with the same title/filename should raise an error message that alerts the user with something like "You already have a document titled duplicate_title.pdf".  Or, at the very least, append "-01", "-02", etc., to duplicated filenames and alert the user or put a note in the log.

#### 3. Add one hierarchical grouping (call it category?) above document_type
Perhaps this is not worth the extra complexity, and I'm also curious to see how your idea of nested tags turns out which may be more elegant.  But, I would like to have something like:

categories = Insurance, Banking, Credit Cards
document_types = Invoices, Statements, Receipts, Letters
```
PAPERLESS_FILENAME_FORMAT={category}/{correspondent}/{document_type}/{title}
```
And end up with:
```
Insurance
  /My Insurance Company
    /Letters
      /2020.12.01 A Letter From My Insurance Company.pdf
Banking/
  /My Bank
    /Statements
      /2020.12.31 December Bank Statement.pdf
Credit Cards
  /My Credit Card Company
    /Statements
      /2020.12.31 December Credit Card Statement.pdf
```
#### 4. Perhaps store the document's metadata in the file itself
I like to think of a document viewer the same way I think about music players/organizers such as Rhythmbox, Amarok, and iTunes.  I keep my digital music files organized in my computer's filesystem,  but I use a music playing app to help me organize and play my music.  Why not store all of a document's metadata in the document itself in the same way that MP3 music files store ID3 tags.  Could this be done with XMP tagging (https://en.wikipedia.org/wiki/Extensible_Metadata_Platform)?

#### 5. One final note
I'm running paperless-ng 0.9.4  in a FreeBSD jail with a "bare metal" install.  Aside from some inotify speed bumps, everything runs fine.

**Comment by jonaswinkler** [comment]
Hello!

Thanks for giving such detailed feedback. This is the stuff that keeps projects like this going.

> First, a little background: I consider myself a database guru, but a mere enthusiast/tinker when it comes to coding python. I used Mayan (https://mayan-edms.com) to organize my home office documents for many years, but found it to be too cumbersome and overly complex for my needs. One thing it did do, however, is force me to think about how to organize my scanned documents in a way that makes sense to me. I've recently pulled all of my documents (~1500) out of Mayan and now store them in a simple file system hierarchy. I went searching for a new tool and found my way to your project, and all I can say is, thank-you. Great work on a great project. It checks all the right boxes for me: keeps it simple, OCRs documents and provides robust searching, stores the documents in the file system in a hierarchical way of my choosing, uses SQLite for simple backups or PostgreSQL (yeah!!) for larger setups, runs in a browser, is written in Python, has an intuitive GUI.

Just remember that half of the credit goes to the original project. :) For example, the entire filename format logic was done by someone else, I just reworked the implementation a bit to make it more maintainable and fail-safe.

> #### 1. Add a placeholder for document type to PAPERLESS_FILENAME_FORMAT

Sure, that's easy. I put it on the list.

> #### 2. Don't alter the filename.
> 1. It's the database's job to uniquely identify a file (it's ID number in this case), and to keep track of where the file is located in the file system.  Removing spaces and capital letters and appending the document ID to the end of the filename is unnecessary and inconvenient to the end-user.

That's partially true. Right now, the title field allows characters that are not valid in file names. When I change this behavior, I have to take that into consideration. Some users may use such titles and renaming would fail.

The current logic makes url-safe filenames. That's not necessarily required, but the implementation is simple and bomb proof. I'll consider using less restrictive conversions, that just remove problematic characters or replace them with dashes, or something.

> 2. Having duplicate titles/filenames would be an error on my part that I want to know about.  Trying to name two documents with the same title/filename should raise an error message that alerts the user with something like "You already have a document titled duplicate_title.pdf".  Or, at the very least, append "-01", "-02", etc., to duplicated filenames and alert the user or put a note in the log.

There's valid reason to have multiple documents with the same title, and putting ids in the title is the safest way of dealing with that. I've got two documents titled "December 2020", both typed "Bank statement", one tagged "account1", the other "account2". I agree it's inconvenient. "-01", "-02" seems like a good idea, I'll keep that in mind. There won't be any errors about duplicate titles, though.

> #### 3. Add one hierarchical grouping (call it category?) above document_type
> Perhaps this is not worth the extra complexity, and I'm also curious to see how your idea of nested tags turns out which may be more elegant. But, I would like to have something like:

I don't see myself adding a new entity type anytime soon. However, we could use tags to specify a "category" for each document type, which you would then be able to reference in the filename format. Or maybe just provide a plain text field for that. I'll think about that once I tackle this hierarchical tags thing. I also thought about scratching types entirely, since they're just a more specific form of tags, but it seems they are rather useful.

> #### 4. Perhaps store the document's metadata in the file itself
> I like to think of a document viewer the same way I think about music players/organizers such as Rhythmbox, Amarok, and iTunes. I keep my digital music files organized in my computer's filesystem, but I use a music playing app to help me organize and play my music. Why not store all of a document's metadata in the document itself in the same way that MP3 music files store ID3 tags. Could this be done with XMP tagging (https://en.wikipedia.org/wiki/Extensible_Metadata_Platform)?

I'd rather not modify the original files at all. Paperless even has checksums in place that make sure they stay the same. I don't want to cause any data loss in case some library decides to wreak havoc. That's also the reason why I decided to keep originals and OCR-enhanced files next to each other with the new update.

Also, we'd need the database anyway for searching and serving data to the front end in a reasonable time. Fetching that data by reading hundreds of files when the users searches for something just won't cut it.

> #### 5. One final note
> I'm running paperless-ng 0.9.4 in a FreeBSD jail with a "bare metal" install. Aside from some inotify speed bumps, everything runs fine.

Glad to hear that!

Honestly, when I started working on this, I thought about removing this filename feature all together, since it was giving me lots of headaches and I thought that users don't care anyway about how the files are stored on disk, but it seems I was wrong.

**Comment by brianwanderson** [comment]
> Just remember that half of the credit goes to the original project. :) For example, the entire filename format logic was done by someone else, I just reworked the implementation a bit to make it more maintainable and fail-safe.

Yes, credit to Daniel Quinn, the original author of paperless and all who contributed to that project.  But, don't sell yourself short.  You've put in a lot of work.

#### 1. Add a placeholder for document type to PAPERLESS_FILENAME_FORMAT

> Sure, that's easy. I put it on the list.

Great.  I was hoping you would say that.  I looked over the code, and it seemed like it might an easy fix.

#### 2. Don't alter the filename.

> The current logic makes url-safe filenames. That's not necessarily required, but the implementation is simple and bomb proof. I'll consider using less restrictive conversions, that just remove problematic characters or replace them with dashes, or something.

Fair enough.  But I still feel that it would be much simpler and more elegant to leverage the file system and simply have the name of the file be the same as the the document title and simply restrict illegal characters or raise an alert box when the user tries to use an illegal character or something like that.  Although, I have to admit, I'm not well versed on how Python deals with illegal characters in file names vs. what operating system and file system the code is running on.  

(As a side rant: If I were the absolute ruler of all things computer, the first thing I would do is have a dedicated path separator key on the keyboard that was not a printed character.  The fact that `/`, `\`, and `:` serve as both printed characters and directory separators is one of the most unfortunate outcomes of history.)

> There's valid reason to have multiple documents with the same title, and putting ids in the title is the safest way of dealing with that. I've got two documents titled "December 2020", both typed "Bank statement", one tagged "account1", the other "account2".

I've been putting a lot of though into this--trying to see things from both sides.  And, I'm afraid I don't agree.  I think you are making things harder on yourself then they need to be.  I find it inadvisable to  design a system that allows both:

**A**
```
% ls  media/documents/originals
December 2020 - 0000001.pdf
December 2020 - 0000002.pdf
```
such that 
file: December 2020 - 0000001.pdf has
 - title attribute set to December 2020
 - tagged as account 1

and file: December 2020 - 0000002.pdf has 
 - title attribute set to December 2020
 - tagged as account 2

and **B**
```
PAPERLESS_FILENAME_FORMAT= {placeholder}/{another_placeholder}/{title}
```
I think that if you want condition A, you shouldn't allow the config setting in B.

One of the main features of both paperless and paperless-ng that I like is the ability to store my documents in a directory structure of my choosing with file names of my choosing.  I've tried other document management systems that put all of the document files in one giant directory and managed all the file names.  I ended up with a directory filled with thousands of PDF files with names like: "ffe24e1f-a5d8-40a6-bb64-708fb8e078d9".  Yuk!

When I go look at my files, I would much rather see something like:
```
PAPERLESS_FILENAME_FORMAT= {document_type}/{title}
% ls media/documents/originals
Bank Statement/December 2020 - account 1.pdf
Bank Statement/December 2020 - account 2.pdf
```
or, alternatively

```
PAPERLESS_FILENAME_FORMAT= {document_type}/{tag[0]}/{title}
% ls media/documents/originals
Bank Statement/account 1/December 2020.pdf
Bank Statement/account 2/December 2020.pdf
```
then
```
PAPERLESS_FILENAME_FORMAT= {document_type}/{title}
% ls media/documents/originals
Bank Statements/December 2020-0000059.pdf
Bank Statements/December 2020-0000060.pdf

or even

Bank Statements/December 2020.pdf
Bank Statements/December 2020-01.pdf

```
side note:
I've found that trying to make directories from tags is clumsy at best.

#### 3. Add one hierarchical grouping (call it category?) above document_type

> I don't see myself adding a new entity type anytime soon.

Fair enough.  That would probably be a heavy lift and would perhaps tip it over the "don't over complicate things" edge.

> I also thought about scratching types entirely, since they're just a more specific form of tags, but it seems they are rather useful.

I think date, correspondent, and document type are the three core attributes and warrant their own special top-level type treatment as currently implemented. 

#### 4. Perhaps store the document's metadata in the file itself

> I'd rather not modify the original files at all.

Agreed.  That would be a big bite to chew.  I tried doing a little more research on the subject of writing XMP tags (https://en.wikipedia.org/wiki/Extensible_Metadata_Platform, https://exiftool.org).  Ugh, what a thorny mess.  I still think the notion of storing a document's metadata within the file itself is the best way to do things.  Unfortunately, I don't think anyone has come up with any good standard way of doing it.

**Comment by jonaswinkler** [comment]
> I've been putting a lot of though into this--trying to see things from both sides. And, I'm afraid I don't agree. I think you are making things harder on yourself then they need to be.

Probably. The thing is, paperless allowed duplicate titles in the past, and therefore, some users will have documents with duplicate titles and I need to take that into consideration. I really like the idea of having _01, _02 at the end of the file name in case that happens and will look into getting that into the code. No impact for users who are not in that situation, and a working solution for users who are.

> side note:
> I've found that trying to make directories from tags is clumsy at best.

I'm open to any recommendations on how to make it better. That part of the code is still in there from original paperless. The idea I'm working on right now looks somewhat like this:

* Placeholder `{tags}` always returns an alphabetically sorted, comma separated list of tags assigned to the document, which might be empty.
* Placeholder `{tags_folder}` would return either 'none' for no tags, the name of a single assigned tag, or 'multiple' for multiple tags.
* Placeholder `{tags_path}` would return a path where each assigned tag is a folder.

Not optimal, since tags don't translate well into folders. There's also the idea of having hierarchical tags over at #56, maybe we can work out something with that.
