### ISSUE TITLE
PDF with ':' in the name fails to upload

### ISSUE THREAD

**Issue by qcasey** [jonaswinkler/paperless-ng#91]
Hello again, I got this weird error when uploading a PDF in the web UI. When a PDF contains a ':' in the filename, the frontend reports

`An error has occured while uploading the document. Sorry! `

The webserver logs:
```
webserver_1  | WARNING 2020-12-05 20:08:55,040 log Bad Request: /api/documents/post_document/
webserver_1  | 172.18.0.1 - - [05/Dec/2020:20:08:55 -0800] "POST /api/documents/post_document/ HTTP/1.1" 400 42 "http://johanna.local:8000/dashboard" "Mozilla/5.0 (X11; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0"
```

I tried a file named "test: test.pdf" which fails, while the same file renamed "test test.pdf" works fine.

First on jonaswinkler/paperless-ng:0.9.3. Tried upgrading to 0.9.5 but the same thing happened. 

Do you think this is a side effect of the filename guesswork?

**Comment by jonaswinkler** [comment]
This is actually on purpose. On Unix systems, the colon is used to separate paths and therefore not allowed in file names, along with a couple other characters. 

Paperless used to store files in the consumption folder with the exact name given during upload, and therefore, someone could upload a file named '../src/documents/apps.py' and the server would overwrite its source with whatever was uploaded.

Paperless ng does this somewhat different, maybe we can remove the file name validation step.

**Comment by qcasey** [comment]
Very interesting - I didn't know that. I'm not sure how necessary the file name validation is.

If we do keep the validation, we should at least update the frontend error message to inform the user.

**Comment by jonaswinkler** [comment]
Alright, I've looked into that and I'm pretty sure the Filename validation step is not required, since:

- Uploaded files are stored in a temporary directory with generated, random names.
- The actual filename given during upload is only ever used to create metadata from the title, such as date, or title.
- When paperless generates filenames for storage in the media directory from this data, it does filename sanitation. So even if someone decides to upload files with crazy file names, we'll always write safely named files to disk.

I'll remove that step and this should fix this issue.

**Comment by qcasey** [comment]
Thanks 😃
