### ISSUE TITLE
Let document exporter export files with their original filenames only

### ISSUE THREAD

**Issue by wechsler42** [jonaswinkler/paperless-ng#94]
Hi Jonas,
would it be possible to optionally let document exporter export files with their original file names only? That means without any preceding numbers etc.. This could be an option in the  document_exporter command.

**Comment by jonaswinkler** [comment]
Paperless does not remember the original filename, it rather gathers information from the filename (i.e., document title) and stores that in the database. When exporting documents (or providing downloads), it generates a filename from that information.

Right now, the filenames have some numbers in them to prevent duplicates in the export folder. This has been an issue before and caused the exporter to silently overwrite some of the exported files, which is really bad. Even if I have the original filename, I could not use that name verbatim for exporting files, since you can add multiple (different) documents with the same filename.

I'm working on making the output of the exporter more usable, with separate folders for documents and thumbnails, and better filenames.

Maybe I need to update the documentation on how paperless handles filenames.

**Comment by wechsler42** [comment]
Thanks for explaining the details I was not aware of and for improving the export feature.
