### ISSUE TITLE
Select multiple documents from search results

### ISSUE THREAD

**Issue by greyduk** [jonaswinkler/paperless-ng#944]
I've been batch importing files by dropping them in the watch folder. I know I should probably use the web interface for these types of things, but I find it easier this way and I'm trying to demonstrate proof of concept to other users. When done this way, the import leaves all the new documents mixed in with the rest based on creation date.

I can currently use the search feature several different ways to find the documents I want to, so that is a great design. The problem is, I can't just go tag them all at once. I have to edit each individual document and add tags. Or I have to go to the main document page and select them that way. The preview feature helps, but it's still more cumbersome than it needs to be.

**Comment by jonaswinkler** [comment]
This is a pretty vague request.

First of all, all methods of getting documents into paperless are equal. It does not matter if you use the watch folder or the web interface, it's all the same.

You can also

* sort by `Date added`, so that recently added documents will show up first / last.
* Search for something, select all documents, and then use the edit dropdowns to mass assign tags / correspondents / etc.
* The document list view also supports range select with shift.

What exactly do you have in mind?

**Comment by greyduk** [comment]
You are correct, and additionally I was unnecessarily verbose.

When you use the filter text input, or any other filter option like tags or document type, you can select multiple documents. When searching documents using the uppermost text input, the results are always what I want to find. I just want to be able to select multiple documents from the resulting list.

I appreciate your quick response, and if this is not deemed worthwhile, I will still be an avid supporter of this project.

**Comment by jonaswinkler** [comment]
What version are you on? I've added exactly that in 1.4.0.

**Comment by greyduk** [comment]
1.3.2. Thank you for this feature and your patience with my request. My docker interface shows mine as up-to-date, but I made the very noob mistake of not verifying versions before posting an issue. I am sorry for wasting your time, and thank you for a great project!
